config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'locations/show'
  get 'top_designers/show'
  get 'top_designers/new'
  get 'top_designers/edit'

  resources :clients
  resources :designers
  resources :top_designers

  root 'top_designers#index'
  get '/locations/:location', to: 'locations#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    has_one :designer       
end

app/models/designer.rb
class Designer < ApplicationRecord
    mount_uploaders :pictures, PictureUploader
    mount_uploader :profile_pic, PictureUploader
    mount_uploader :design_image, PictureUploader
    has_many :clients

    def self.search(search)
        where("first_name ILIKE ? OR last_name ILIKE ? OR company_name ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%") 
    end
end

app/models/top_designer.rb
class TopDesigner < ApplicationRecord
    def self.search(search)
        where("first_name ILIKE ? OR last_name ILIKE ? OR company_name ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%") 
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
 
    before_action :authenticate_user!
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, :only => [:index]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Account was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :email, :location, :user_id)
    end
end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController
  before_action :set_designer, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, :only => [:index]

  # GET /designers
  # GET /designers.json
  def index
    @designers = Designer.all
    if params[:search]
      @designers = Designer.search(params[:search]).order("created_at DESC")
    else
      @designers = Designer.all.order("created_at DESC")
    end
  end

  # GET /designers/1
  # GET /designers/1.json
  def show
    if params[:search]
      @designers = Designer.search(params[:search]).order("created_at DESC")
    else
      @designers = Designer.all.order("created_at DESC")
    end
  end

  # GET /designers/new
  def new
    @designer = Designer.new
  end

  # GET /designers/1/edit
  def edit
  end

  # POST /designers
  # POST /designers.json
  def create
    @designer = Designer.new(designer_params)

    respond_to do |format|
      if @designer.save
        format.html { redirect_to @designer, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @designer }
      else
        format.html { render :new }
        format.json { render json: @designer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designers/1
  # PATCH/PUT /designers/1.json
  def update
    respond_to do |format|
      if @designer.update(designer_params)
        format.html { redirect_to @designer, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @designer }
      else
        format.html { render :edit }
        format.json { render json: @designer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designers/1
  # DELETE /designers/1.json
  def destroy
    @designer.destroy
    respond_to do |format|
      format.html { redirect_to designers_url, notice: 'Account was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_designer
      @designer = Designer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def designer_params
      params.require(:designer).permit(:first_name, :last_name, :email, :phone_number, :company_name, :company_website, :profile_pic, :design_image, :location, :user_id, :remove_profile_pic, :remove_design_image, :about, :designer_id, :company_slogan, :designer, pictures:[])
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def show
    @designers_from_location = Designer.where(location: params[:location])
    puts @designers_from_location
  end
end

app/controllers/top_designers_controller.rb
class TopDesignersController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  def index
    @featured_designers = Designer.where('location IS NOT NULL').group(:location).order('count_id DESC').limit(6).count(:id)    
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/design_professionals_helper.rb
module DesignProfessionalsHelper
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/top_designers_helper.rb
module TopDesignersHelper
    
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.first_name %></td>
        <td><%= client.last_name %></td>
        <td><%= client.email %></td>
        <td><%= client.location %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Delete', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

<% if current_user.nil? %>
	<%= link_to new_user_session_path, class: 'login-button' do %>Sign in<% end %>
<% else %>
	<%= link_to new_client_path, class: 'login-button' do %>Go to App<% end %>
<% end %>

<% if user_signed_in? %>
 
  <%= link_to('Edit registration', edit_user_registration_path) %>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
 
<% else %>
 
  <%= link_to('Register', new_user_registration_path)  %>
  <%= link_to('Login', new_user_session_path)  %>  
 
<% end %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @client.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @client.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Location:</strong>
  <%= @client.location %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/designers/_form.html.erb
<%= form_with(model: designer, local: true, html: { multipart: true }) do |form| %>
  <% if designer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(designer.errors.count, "error") %> prohibited this designer from being saved:</h2>

      <ul>
      <% designer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pictures %>
    <%= form.file_field :pictures, multiple: true, accept: "image/jpeg, image/jpg, image/gif, image/png" %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name %>
  </div>

  <div class="field">
    <%= form.label :company_website %>
    <%= form.text_field :company_website %>
  </div>

  <div class="field">
    <%= form.label :profile_pic %>
    <%= form.file_field :profile_pic, id: :designer_profile_pic %>
      <% if form.object.profile_pic? %>
        <%= image_tag form.object.profile_pic.thumb.url %>
        <%= form.label :remove_profile_pic %>
        <%= form.check_box :remove_profile_pic %>
      <% end %>
  </div>

  <div class="field">
    <%= form.label :design_image %>
    <%= form.file_field :design_image, id: :designer_design_image %>
      <% if form.object.design_image? %>
        <%= image_tag form.object.design_image.thumb.url %>
        <%= form.label :remove_design_image %>
        <%= form.check_box :remove_design_image %>
      <% end %>      
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_field :about %>
  </div>

  <div class="field">
    <%= form.label :company_slogan %>
    <%= form.text_field :company_slogan %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/designers/edit.html.erb
<h1>Editing Designer</h1>

<%= render 'form', designer: @designer %>

<%= link_to 'Show', @designer %> |
<%= link_to 'Back', designers_path %>

app/views/designers/index.html.erb
<p id="notice"><%= notice %></p>
<% if @designers.blank? %>
  <h4 class="text-center">There are no current Design Firms with the name <%= params[:search] %>.</h4>
<% end %>

<h1 class="header text-center">Design Lookbook</h1>
<div class="container">
  <div class="row col-s-4 text-center justify-content-center" style="margin-bottom: 5rem;">
      <% @designers.each do |designer| %>
        <div class="card justify-content-center">
          <%= image_tag(designer.design_image_url, width: 400, height:250) if designer.design_image.present? %>
          <div class="avatar justify-content-center">
            <%= image_tag(designer.profile_pic_url, width: 150, height:150) if designer.profile_pic.present? %>
          </div>
          <div class="card-body">
            <h5 class="card-title card-dark text-center"><%= link_to designer.company_name, designer %></h5>
            <a class="card-text text-center"><%= designer.company_website %></a>
          </div>
          <div class="card-footer" style="background-color: #D2D2DB;">
            <ul class="list-group list-group-flush" style="background-color: #D2D2DB;">
              <li class="list-group-item text-center" style="background-color: #D2D2DB;"><%= designer.location %></li>
            </ul>
          </div>  
        </div>
      <% end %>
    </div>
  </div>
</div>


        <h1 class="text-center">Admin Design Firms Table</h1>

        <table class="table thead-dark table-bordered span-12">
          <thead class="table thead-dark">
            <tr>
              <th style="width: 9%">First name</th>
              <th style="width: 8%">Last name</th>
              <th style="width: 9%">Email</th>
              <th style="width: 9%">Phone number</th>
              <th style="width: 9%">Company name</th>
              <th style="width: 9%">Company Slogan</th> 
              <th style="width: 9%">Company website</th>
              <th style="width: 9%">Design image</th>
              <th style="width: 9%">Location</th>
              <th style="width: 9%">Show</th>
              <th style="width: 9%">Edit</th>
              <th style="width: 9%">Delete</th>      
              <th colspan="12"></th>
            </tr>
          </thead>

          <table class="table table-striped table-bordered">
            <tbody>
              <% @designers.each do |designer| %>
                <tr>
                  <td><%= designer.first_name %></td>
                  <td><%= designer.last_name %></td>
                  <td><%= designer.email %></td>
                  <td><%= designer.phone_number %></td>
                  <td><%= designer.company_name %></td>
                  <td><%= designer.company_slogan %></td>
                  <td><%= designer.company_website %></td>
                  <td><%= image_tag(designer.design_image_url, width: 100, height: 100) if designer.design_image.present? %></td>
                  <td><%= designer.location %></td>        
                  <td><%= link_to 'Show', designer %></td>
                  <td><%= link_to 'Edit', edit_designer_path(designer) %></td>
                  <td><%= link_to 'Delete', designer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </table>

        <br>

        <%= link_to 'New Designer', new_designer_path %>

        <% if user_signed_in? %>
          <%= link_to('Edit registration', edit_user_registration_path) %>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
        <% else %> 
          <%= link_to('Register', new_user_registration_path)  %>
          <%= link_to('Login', new_user_session_path)  %>  
        <% end %>  
        </div>

<!-- The Second Modal -->

<div class="container mt-3">
  <!-- Button to Open the Modal -->
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newDesigner">
    Register
  </button>

  <!-- The Modal -->
  <div class="modal fade" id="newDesigner" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title text-center">New Designer Registration</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">

        <!-- Modal footer -->
        <div class="modal-footer">
          <div class="actions">
          </div>
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div> 
      </div>
    </div>
  </div>

</div>

app/views/designers/new.html.erb
<h1>New Designer</h1>

<%= render 'form', designer: @designer %>

<%= link_to 'Back', designers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Avid Design</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'main' %>
  </head>

  <body>
    <header class="mb-5">
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="navbar-brand">Avid Design</div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/designers">Designers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/clients">Clients</a>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
          <%= form_tag(designers_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search Designers" %>
            <button class="btn btn-outline-success my-2 my-sm-0"><%= submit_tag "Search", :name => nil %></button>
            <% end %>
          </form>
        </div>
      </nav>
    </header>

    <% unless flash.empty? %>
        <script type="text/javascript">
              <% flash.each do |f| %>
            <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
            toastr['<%= type %>']('<%= f[1] %>');
        <% end %>
        </script>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
    <%= render "/shared/footer" %>   
  </body>
</html>

app/views/locations/show.html.erb
<h1>Locations#show</h1>
<p>Find me in app/views/locations/show.html.erb</p>

app/views/shared/_carousel.html.erb
<main role="main">

      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
            <div class="container">
              <div class="carousel-caption text-left">
                <h1>Example headline.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Another example headline.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
            <div class="container">
              <div class="carousel-caption text-right">
                <h1>One more for good measure.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
              </div>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

app/views/shared/_footer.html.erb
      <!-- FOOTER -->
      <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; Avid Design, Inc. <%= Time.now.year %> &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
        <div class="container">
            
        </div>
      </footer>
   

app/views/shared/_header.html.erb
    <header class="mb-5">
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="navbar-brand">Avid Design</div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/designers">Designers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/clients">Clients</a>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
          <%= form_tag(designers_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search Interior Design Firms" %>
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><%= submit_tag "Search", :name => nil %></button>
            <% end %>
          </form>
        </div>
      </nav>
    </header>

app/views/top_designers/edit.html.erb
<h1>TopDesigners#edit</h1>
<p>Find me in app/views/top_designers/edit.html.erb</p>

app/views/top_designers/new.html.erb
<h1>TopDesigners#new</h1>
<p>Find me in app/views/top_designers/new.html.erb</p>

app/views/top_designers/show.html.erb
<h1>TopDesigners#show</h1>
<p>Find me in app/views/top_designers/show.html.erb</p>